#!/usr/bin/env bash
# VoiceOrderAI — local machine setup (Linux).
# Creates a venv, installs dependencies, and writes a .env (mode 0600)
# from values you paste in. Secrets are never printed or logged.
set -euo pipefail

cd "$(dirname "$0")"

need() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: $1 not found. Please install it first."; exit 1; }; }
need python3

PYVER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
python3 -c 'import sys; assert sys.version_info >= (3, 10), "need >= 3.10"' \
  || { echo "ERROR: Python >= 3.10 required (found $PYVER)."; exit 1; }

echo "==> Creating virtualenv (.venv)…"
[ -d .venv ] || python3 -m venv .venv
.venv/bin/pip -q install --upgrade pip
echo "==> Installing VoiceOrderAI dependencies…"
.venv/bin/pip -q install .

echo
echo "Now I'll collect the secrets. Paste each value and press Enter."
echo "(Values are hidden while you type. Nothing is printed back.)"
echo

ask() { # ask <VAR> <prompt> <default>
  local var="$1" prompt="$2" default="${3-}" val
  if [ -n "$default" ]; then
    read -rsp "$prompt [$default]: " val; echo
    val="${val:-$default}"
  else
    read -rsp "$prompt: " val; echo
  fi
  printf -v "$var" '%s' "$val"
}

ask ANTHROPIC_API_KEY        "Anthropic API key (from console.anthropic.com)"
ask ANTHROPIC_MODEL          "Anthropic model" "claude-haiku-4-5-20251001"
ask ELEVENLABS_API_KEY       "ElevenLabs API key (xi-api-key, free plan is fine)"
ask TWILIO_ACCOUNT_SID       "Twilio Account SID"
ask TWILIO_AUTH_TOKEN        "Twilio Auth Token (from Twilio console)"
ask TWILIO_PHONE_NUMBER      "Twilio phone number" "+15622680097"
ask PUBLIC_BASE_URL          "Public base URL (your ngrok https URL, e.g. https://xxxx.ngrok-free.app — no trailing slash; leave empty for now, set it after ngrok is up)"
ask RESTAURANT_NAME          "Restaurant name" "Hyderabad House"
ask SQUARE_LOCATION_ID       "Square location ID" "LP080BBB3A045"

[ -z "$ANTHROPIC_API_KEY" ] && { echo "ERROR: ANTHROPIC_API_KEY is required."; exit 1; }
[ -z "$ELEVENLABS_API_KEY" ] && { echo "ERROR: ELEVENLABS_API_KEY is required for voice."; exit 1; }

VOICE_SECRET=$(.venv/bin/python -c 'import secrets; print(secrets.token_urlsafe(32))')
OWNER_SECRET=$(.venv/bin/python -c 'import secrets; print(secrets.token_urlsafe(16))')

[ -f .env ] && cp .env ".env.bak.$(date +%Y%m%d-%H%M%S)" && echo "Backed up existing .env"

cat > .env <<EOF
# Generated by setup.sh on $(date -u +%FT%TZ). Mode 0600. Do not share.
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
VOICE_SECRET=$VOICE_SECRET
OWNER_SECRET=$OWNER_SECRET
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
ANTHROPIC_MODEL=$ANTHROPIC_MODEL
ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY
TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
RESTAURANT_NAME=$RESTAURANT_NAME
POS_PROFILE=square
SQUARE_LOCATION_ID=$SQUARE_LOCATION_ID
SQUARE_ENVIRONMENT=production
SQUARE_MENU_SYNC=1
TTS_ENABLED=1
EOF
chmod 600 .env

echo
echo "==> Verifying install…"
.venv/bin/python -c "import voiceorder.api.main; print('app imports OK')"

echo
echo "=============================================================="
echo " Setup complete. Your owner-dashboard password:"
echo "   $OWNER_SECRET"
echo " (Save it — it's the OWNER_SECRET for /owner and /portal.)"
echo "=============================================================="
echo
echo "Next:"
echo "  1. Start the app:   ./run.sh"
echo "  2. In another terminal, start ngrok:  ngrok http 8000"
echo "  3. Put the ngrok https URL into .env as PUBLIC_BASE_URL and restart ./run.sh"
echo "  4. Send the ngrok URL to Hulk — he'll point your Twilio number at it."
echo "Then call +1 562 268 0097 from your verified mobile to test."
